import { Achievement } from "./types";

export const achievements: Achievement[] = [
  {
    id: "frc-global-ranking",
    title: "Top 3% Global FRC Ranking",
    year: "2026",
    category: "robotics",
    description: "Drove FRC 2813 to a top 3% global ranking among all FIRST Robotics Competition teams.",
    metric: "Top 3%",
    links: [{ label: "The Blue Alliance", href: "https://www.thebluealliance.com/team/2813", type: "blue-alliance" }],
  },
  {
    id: "frc-regional-finalist",
    title: "4× Regional Finalist",
    year: "Tenure",
    category: "robotics",
    description: "Secured 4 Regional Finalist titles during tenure as VP.",
    metric: "4 titles",
    links: [{ label: "The Blue Alliance", href: "https://www.thebluealliance.com/team/2813", type: "blue-alliance" }],
  },
  {
    id: "frc-worlds",
    title: "3× World Championship Invitations",
    year: "Tenure",
    category: "robotics",
    description: "Earned 3 World Championship invitations.",
    metric: "3 invites",
    links: [{ label: "The Blue Alliance", href: "https://www.thebluealliance.com/team/2813", type: "blue-alliance" }],
  },
  {
    id: "funding",
    title: "$100K+ Funding Raised",
    year: "Tenure",
    category: "leadership",
    description: "Raised $100K+ in funding through sponsorships and grants.",
    metric: "$100K+",
  },
  {
    id: "outreach",
    title: "430+ Outreach Hours, 5,000+ Students",
    year: "Tenure",
    category: "leadership",
    description: "Mobilized members for 430+ outreach hours reaching 5,000+ students.",
    metric: "5K+ students",
  },
  {
    id: "green-ninja",
    title: "Green Ninja Film Festival Winner",
    year: "2025",
    category: "environmental",
    description: "Award-winning environmental media project highlighting actionable ecological solutions.",
    metric: "1st Place",
    links: [{ label: "Green Ninja Film Festival", href: "https://web.greenninja.org/resources-gnff", type: "website" }],
  },
  {
    id: "sanskrit-national",
    title: "2nd Place National Sanskrit Competition",
    year: "2025",
    category: "academic",
    description: "Second place among 70+ competitors in national-level Sanskrit recitation.",
    metric: "2nd Place",
  },
  {
    id: "mythri-dance",
    title: "3rd Place Mythri Dance Competition",
    year: "2025, 2026",
    category: "arts",
    description: "Third place at the Mythri Dance Competition for Bharatnatyam performance, two consecutive years.",
    metric: "3rd (×2)",
    links: [
      { label: "Tabla Niketan 2025 Exam", href: "https://www.tablaniketan.com/wp-content/uploads/2025/10/Nov-Dec-2025-Bharatnatyam-Exam-Time-Table.pdf", type: "website" },
      { label: "Tabla Niketan 2024 Exam", href: "https://www.tablaniketan.com/wp-content/uploads/2024/10/Bharatnatyam-Time-Table-Nov-2024.pdf", type: "website" },
    ],
  },
  {
    id: "electrical-growth",
    title: "Electrical Team 6→25 Members",
    year: "2024–2026",
    category: "leadership",
    description: "Grew electrical subteam from 6 to 25 members through structured mentorship.",
    metric: "6 → 25",
  },
  {
    id: "female-participation",
    title: "Female Participation 4→12 (Tripled)",
    year: "2024–2026",
    category: "leadership",
    description: "Intentionally tripled female participation in electrical through mentorship.",
    metric: "4 → 12",
  },
  {
    id: "battery-safety",
    title: "Battery Safety Standards Adopted by 20+ Teams",
    year: "2025",
    category: "robotics",
    description: "Pioneered battery safety standards adopted by 20+ FIRST teams nationwide.",
    metric: "20+ teams",
  },
  {
    id: "sanskrit-growth",
    title: "Sanskrit Program 470% Growth",
    year: "2019–Present",
    category: "academic",
    description: "Scaled enrollment 7 → 40 students, sustaining 90% retention.",
    metric: "470%",
  },
  {
    id: "mesa-students",
    title: "40 MESA Students Tutored",
    year: "2024–Present",
    category: "teaching",
    description: "Weekly individualized tutoring for 40 MESA students in math and science.",
    metric: "40 students",
  },
  {
    id: "soap-growth",
    title: "SOAP@PHS Founded, 10→40 Members",
    year: "2023–Present",
    category: "leadership",
    description: "Founded SOAP@PHS and scaled membership 300% from 10 to 40 students.",
    metric: "300% growth",
  },
];