import { EngineeringSystem } from "./types";

export const engineeringSystems: EngineeringSystem[] = [
  {
    id: "battery",
    name: "Battery",
    description: "12V SLAM battery — primary energy source for all robot systems. Custom safety protocols for handling, charging, and monitoring.",
    category: "power",
    details: "Pioneered battery safety standards adopted by 20+ FRC teams. Includes thermal monitoring, charge/discharge logging, and fail-safe disconnects.",
    connections: ["pdu"],
  },
  {
    id: "pdu",
    name: "Power Distribution",
    description: "REV Power Distribution Hub / PDU — manages power delivery from battery to all subsystems with per-circuit current limiting and monitoring.",
    category: "power",
    details: "Custom PDU wiring harness with labeled, strain-relieved connections. Integrated current sensing for brownout prevention.",
    connections: ["can-bus", "motor-controllers", "roborio", "radio"],
  },
  {
    id: "can-bus",
    name: "CAN Bus",
    description: "CAN 2.0B network — system communication backbone connecting motor controllers, sensors, and RIO. 1 Mbps baud, terminated ends.",
    category: "communication",
    details: "Star topology with central junction. Device IDs allocated by subsystem. Real-time telemetry streaming to dashboard.",
    connections: ["motor-controllers", "pneumatics", "sensors", "vision", "swerve"],
  },
  {
    id: "motor-controllers",
    name: "Motor Controllers",
    description: "REV Spark MAX / Talon FX — brushless motor control with integrated PID, current limiting, and CAN telemetry.",
    category: "actuation",
    details: "4× Spark MAX for swerve drive (azimuth + drive per module), 2× for intake, 1× for elevator. Firmware synchronized.",
    connections: ["swerve", "intake", "elevator", "climber"],
  },
  {
    id: "swerve",
    name: "Swerve Drive",
    description: "MK4i / MK5N modules — 4-wheel independent steering + drive. NEO / Falcon 500 motors with integrated absolute encoders.",
    category: "actuation",
    details: "Odometry via module absolute encoders + gyro. PathPlanner auto trajectories. Module calibration routine on init.",
    connections: ["motor-controllers", "gyro", "odometry"],
  },
  {
    id: "gyro",
    name: "IMU / Gyro",
    description: "Pigeon 2.0 / NavX — 9-axis IMU for heading, rate, and acceleration. Fused with wheel odometry for pose estimation.",
    category: "sensing",
    details: "CAN-connected. Temperature-compensated calibration. Used for field-centric drive and autonomous heading control.",
    connections: ["swerve", "odometry"],
  },
  {
    id: "vision",
    name: "Vision System",
    description: "PhotonVision / Limelight — AprilTag detection, object tracking, pose estimation. Coprocessor offloads image processing.",
    category: "sensing",
    details: "Dual-camera setup (wide + narrow FOV). AprilTag mapping for auto alignment. NetworkTables / NT4 publishing.",
    connections: ["can-bus", "networktables"],
  },
  {
    id: "pneumatics",
    name: "Pneumatics",
    description: "REV Pneumatics Hub — compressor, pressure sensor, solenoid valves. Controls intake deployment, climber actuation.",
    category: "actuation",
    details: "Pressure-regulated at 70 PSI. Solenoids on CAN. Watchdog timer prevents runaway compressor.",
    connections: ["can-bus", "intake", "climber"],
  },
  {
    id: "intake",
    name: "Intake / Collector",
    description: "Roller-based game piece acquisition with beam-break sensors. Motor: NEO 550 / Falcon 500. Compliant geometry.",
    category: "actuation",
    details: "Sensor-triggered auto-indexing. Current-based stall detection. Pneumatic deployment for ground clearance.",
    connections: ["motor-controllers", "pneumatics", "sensors"],
  },
  {
    id: "elevator",
    name: "Elevator / Arm",
    description: "Cascade elevator with cable-driven carriage. NEO motor + absolute encoder. Soft limits at travel extremes.",
    category: "actuation",
    details: "Motion profiling for smooth motion. Counterbalance spring assist. Brake mode holds position when disabled.",
    connections: ["motor-controllers", "sensors"],
  },
  {
    id: "climber",
    name: "Climber",
    description: "Telescoping or hook-based ascent mechanism. High-torque motor + ratchet. Pneumatic trigger release.",
    category: "actuation",
    details: "Redundant engagement verification. Mechanical latch as backup. End-of-match auto-deploy sequence.",
    connections: ["motor-controllers", "pneumatics"],
  },
  {
    id: "roborio",
    name: "roboRIO 2.0",
    description: "Central controller — runs robot code, CAN master, NI Linux RT. Interfaces with all subsystems via CAN, DIO, SPI.",
    category: "control",
    details: "Java/Kotlin + WPILib. Periodic tasks at 50Hz/100Hz. NetworkTables for dashboard. ROMI-compatible for simulation.",
    connections: ["can-bus", "pdu", "radio", "networktables"],
  },
  {
    id: "radio",
    name: "Radio / Wireless",
    description: "VH-109 / OpenMesh — 2.4/5 GHz field wireless. FMS handshake, bandwidth management, QoS for control streams.",
    category: "communication",
    details: "Dedicated control VLAN. mDNS for device discovery. Mesh backup for pit networking.",
    connections: ["pdu", "roborio"],
  },
  {
    id: "networktables",
    name: "NetworkTables 4",
    description: "Publish-subscribe data layer — telemetry, tuning, vision poses, autonomous selectors. Real-time dashboard sync.",
    category: "communication",
    details: "NT4 with topic-based schema. Persistent keys for preferences. Structured logging for post-match analysis.",
    connections: ["roborio", "vision", "dashboard"],
  },
];